# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.   


In [2]:
import numpy as np

In [3]:
# ejercicio 1
a = np.array([1, 2, 3, 4])
if np.all(a != 0):
    print("Ninguno de los elemenmtos es 0")
else:
    print("hay al menos un 0 en el arreglo")


Ninguno de los elemenmtos es 0


In [ ]:
# ejercicio 2
a = np.array([0, 0, 2, 0])
if np.all(a == 0):
    print("no hay elementos diferentes de 0")
else:
    print("Hay al menos un elemento diferente de 0")


Hay al menos un elemento diferente de 0


In [17]:
# ejercicio 3
a = np.array([1, 2, np.nan, np.inf])
np.isnan(a).any() or np.isinf(a).any()
print(f"NaN encontado en: {np.isnan(a)}")
print(f"Inf encontado en: {np.isinf(a)}")

NaN encontado en: [False False  True False]
Inf encontado en: [False False False  True]


In [19]:
# ejercicio 4
a = np.array([1, 2, np.inf])
np.isinf(a).any()
print(f"Inf encontado en: {np.isinf(a)}")


Inf encontado en: [False False  True]


In [20]:
# ejercicio 5
a = np.array([1, np.nan, 3])
np.isnan(a).any()
print(f"NaN encontado en: {np.isnan(a)}")


NaN encontado en: [False  True False]


In [7]:
# ejercicio 6
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])

resultado = np.where(a > b, "mayor", np.where(a == b, "igual", "menor"))
print(resultado)

['menor' 'igual' 'mayor']


In [16]:
# ejercicio 7
a = np.array([1, 7, 13, 105])


print(f"Arreglo {a}")
print(f"Memoria ocupada: {a.nbytes} bytes")
print(f"Tipo de dato: {a.dtype}")
print(f"NUmero de elementos: {a.size}")
print(f"Bytes por elemento: {a.itemsize}")

Arreglo [  1   7  13 105]
Memoria ocupada: 32 bytes
Tipo de dato: int64
NUmero de elementos: 4
Bytes por elemento: 8


In [18]:
# ejecicio 8
ceros = np.zeros(10)
unos = np.ones(10)
cincos = np.full(10, 5)
print(ceros)
print(unos)
print(cincos)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]


In [20]:
#ejercicio 9
a = np.arange(30,71)
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [22]:
#ejercicio 10
a = np.arange(30,71,2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [6]:
# ejercicio 11
M1 = np.eye(3)
print(M1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [69]:
# ejercico 12
rng = np.random.default_rng()
num = rng.random() 
print(num)

0.6293456350011999


In [72]:
# ejercicio 13
rng = np.random.default_rng()
arreglo = rng.standard_normal(15)
print(arreglo)

[ 0.39325709 -0.22536008 -0.99282378  1.38693203  0.4722048  -0.30032964
 -0.45435679  0.69304244  1.70833315  0.51466717  0.44945026 -0.06230048
  0.35909854 -0.6146877  -0.41900837]


In [77]:
# ejercicio 14
arreglo = np.arange(15, 56)
print(arreglo[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [5]:
# ejercicio 15
arreglo = np.linspace(5, 50,10 ) # del 5 al 50 y el 3ero es de cuantos numeros quiero entre ese rango
print(arreglo)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:

# ejercicio 16
arr = np.arange(21)  # valores de 0 a 20
print("Original:", arr)
mask = (arr >= 9) & (arr <= 15)  # números de 9 a 15
arr[mask] *= -1  # cambia el signo
print("Modificado:", arr)
# ...existing code...

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Modificado: [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [ ]:
#ejercicio 17
a = np.array([1, 2, 3])
print(f"Array de numpy: {a}")
print("Tipo:", type(a))#esto es para ver el tipo de dato que es la variable a

lista = a.tolist()#convertir el Array a lista de python
print(f"Lista de python: {lista}")
print("Tipo:", type(lista))

Array de numpy: [1 2 3]
Tipo: <class 'numpy.ndarray'>
Lista de python: [1, 2, 3]
Tipo: <class 'list'>


In [18]:
#ejercicio 18
l = [1, 2, 3]
print(f"Lista en python: {l}")
print("Tipo:", type(l))

Arr = np.array(l)
print(f"Array en numpy: {Arr}")
print("Tipo:", type(Arr))

Lista en python: [1, 2, 3]
Tipo: <class 'list'>
Array en numpy: [1 2 3]
Tipo: <class 'numpy.ndarray'>


In [27]:
#ejercicio 19
m = np.array([[1, 2], [3, 4]])
print("Matriz original:")
print(m)

resultado = (m % 2 == 0)
print("\nMatriz de resultados (True = par, False = impar):")
print(resultado)

Matriz original:
[[1 2]
 [3 4]]

Matriz de resultados (True = par, False = impar):
[[False  True]
 [False  True]]


In [32]:
#ejercicio 20
m = np.array([[1, 2, 3], [4, 5, 6]])

filas, columnas = m.shape
print(f"Total de filas: {filas}")
print(f"Total de columnas: {columnas}")

Total de filas: 2
Total de columnas: 3
